---
apiVersion: v1
kind: Pod
metadata:
  name: {{ name }}
  labels:
    {{ label }}: {{ labelValue }}
spec:
  containers:
    - name: {{ containerName }}
      image: {{ imageName }}
      ports:
        - containerPort: {{ port }}
      volumes:
        data: