---
apiVersion: v1
kind: {{ kind }}
metadata:
  name: {{ name }}
  labels:
    {{ label }}: {{ labelValue }}
spec:
  replicas: 1
    selector:
      matchLabels:
        {{ label }}: {{ labelValue }}
    template:
      metadata:
        labels:
          {{ label }}: {{ labelValue }}
  containers:
    - name: {{ containerName }}
      image: {{ imageName }}
      ports:
        - containerPort: {{ port }}