---
apiVersion: v1
kind: {{ kind }}
metadata:
  name: {{ name }}
  labels:
    {{ label }}: {{ labelValue }}
spec:
  containers:
    - name: {{ containerName }}
      image: {{ imageName }}
      ports:
        - containerPort: {{ port }}